### ISSUE TITLE
Where are iter_cot_weak.py and iter_cot_strong.py?

### ISSUE THREAD

**Issue by xihuai18** [GasolSun36/Iter-CoT#1]

**Comment by GasolSun36** [comment]
Thank you for your interest in our work! 😉This project is still developing, and we will update both files to the repo as soon as we can.

**Comment by GasolSun36** [comment]
We're finally open-sourcing our complete code. 😉😉

**Comment by GasolSun36** [comment]
We're finally open-sourcing our complete code. 😉😉
