### ISSUE TITLE
Code Available?

### ISSUE THREAD

**Issue by gsprint23** [GasolSun36/Iter-CoT#3]
Hello. Referring to your README: "code will be publicly avaliable when paper is accepted." Is the paper accepted? When will the code be available? I'm particularly interested in learning from your use of llama 2. Thanks.

**Comment by GasolSun36** [comment]
Hi, sorry I've been so busy lately for organizing the code and new README. You can refer to my other project code, which describes in detail how to use the llama2: [https://github.com/GasolSun36/ToG/tree/main/CoT](https://github.com/GasolSun36/ToG/tree/main/CoT)
